### PR TITLE
Update Yann

### PR DESCRIPTION
**Pull request by YannDubs**
Description: Same submission as [before](https://github.com/stanford-cs336/spring2024-assignment1-basics-leaderboard/pull/11#issue-2245209778) but I slightly tuned the lr. Still no architecture changes (besides width/depth).
Link: https://api.wandb.ai/links/hashimoto-group/5t1e2wjd

Fun assignment 👍

### CODE REVIEW

**Comment by nelson-liu** [comment]
i think the wandb link only shows the train loss?

**Comment by YannDubs** [comment]
added val & train, I find train to be more telling because it's off by a max of 0.01 but is much more fine-grained!

**Comment by nelson-liu** [comment]
yeah, i agree that train should more-or-less be the same as validation in this particular setting. the new link seems to 404 for me

**Comment by YannDubs** [comment]
added access, sorry!

**Comment by nelson-liu** [comment]
still no dice on the link that's in the diff :( https://wandb.ai/hashimoto-group/cs336_assignment1/reports/train-loss-24-04-16-15-48-29---Vmlldzo3NTc0MTQ5

**Comment by YannDubs** [comment]
ok last try, sorry @nelson-liu . If doesn't work feel free to close, I mostly just wanted to know for myself how much lr tuning helps.

**Comment by nelson-liu** [comment]
works now, sorry for all the hassle!

**Pull request merged**
